"""init tables: host_star, planet, merchant, user

Revision ID: fb24bbc4e3a0
Revises: 
Create Date: 2025-05-12 18:28:19.709163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb24bbc4e3a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_star',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=128), nullable=False),
    sa.Column('sy_pnum', sa.Integer(), nullable=True),
    sa.Column('sy_dist', sa.Float(), nullable=True),
    sa.Column('sy_disterr1', sa.Float(), nullable=True),
    sa.Column('sy_disterr2', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hostname')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pl_name', sa.String(length=128), nullable=False),
    sa.Column('discoverymethod', sa.String(length=64), nullable=True),
    sa.Column('disc_year', sa.Integer(), nullable=True),
    sa.Column('disc_facility', sa.String(length=128), nullable=True),
    sa.Column('host_star_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['host_star_id'], ['host_star.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planet')
    op.drop_table('user')
    op.drop_table('host_star')
    # ### end Alembic commands ###
